name: Deploy to Netlify

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build
        env:
          VITE_SUPABASE_URL: "https://sagyopsmbkylppyivpoe.supabase.co"
          VITE_SUPABASE_PUBLISHABLE_KEY: "sb_publishable_nYMFye-t9tDcSDr9_4u3rQ_pllpO3yu"
          VITE_SUPABASE_PROJECT_ID: "sagyopsmbkylppyivpoe"

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        run: netlify deploy --prod --dir=.output/public --site=112b4479-db85-4364-9fc4-7c554ee163e5 --auth=nfp_rfqfz3GtnNJZqZidcjCCW5Rmke2rSxZV7f81
